// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mwchdglkvjtutajdwjjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13Y2hkZ2xrdmp0dXRhamR3ampyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTU1NDgsImV4cCI6MjA3MTE5MTU0OH0.JjxMJexpzzm4c9l3mILsLzVbnvarwcIPvpn_JzhJKTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);